### ISSUE TITLE
Change a file and push the changes to test the connection between github and server.

### ISSUE THREAD

**Issue by aoengin** [cbystam/Continuous-integration#9]
A file should be changed to observe if the github properly sends a webhook request to the server.

**Comment by cbystam** [comment]
Testing webhook triggering with issue commenting. Editing to trigger. Editing again. And again. So many edits. All of them, in fact. Another one. This too. Yep. And here.

**Comment by cbystam** [comment]
Testing was changed to trigger on commits, for testing. Triggering worked, so closing the issue.
